# Generated by Django 6.0.5 on 2026-05-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together={('article', 'index')},
        ),
    ]
