# Generated by Django 6.0.5 on 2026-05-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_otp_remove_customuser_otp_attempt_and_more'),
        ('article', '0002_alter_paragraph_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('profile', 'article')},
        ),
    ]
